on: workflow_dispatch
name: test workflow

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: get and replace values yaml
        run: |
          ls -la
