name: test workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get and replace values yaml
        run: |
          ls -la
          cd vestible-ms
          echo "getting old image value"
          prevImage=$(cat values.yaml | grep "image" | cut -c 10-)
          echo "updating values.yaml to change docker image"
          sed -i '' "s#$prevImage#961118838869.dkr.ecr.us-east-1.amazonaws.com/vestible-gateway:latest#g" values.yaml
          helm template vestible-ms ./ 
