name: test workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set git commit sha as tag
        id: set-tag
        run: echo "::set-output name=tag::$(git rev-parse --short ${{ github.sha }})"

      - name: get and replace values yaml
        run: |
          echo "updating values.yaml to change docker image"
          sed -i "s#defaultImage#961118838869.dkr.ecr.us-east-1.amazonaws.com/vestible-gateway:${{ steps.set-tag.outputs.tag }}#g" ./vestible-ms/values.yaml
          helm template vestible-ms ./vestible-ms
